version: 2.1

orbs:
  android: circleci/android@2.4.0
jobs:
  test:
    description: Runs unit tests and instrumented tests on the Survey app
    executor:
      name: android/android-machine
      resource-class: large
      tag: 2024.01.1

    steps:
      - checkout
      - run:
          name: Chmod Permissions
          command: sudo chmod +x gradlew

      - android/create-avd:
          avd-name: avd
          install: true
          system-image: system-images;android-30;default;x86_64
          additional-args: --sdcard 2048M

      - android/start-emulator:
          avd-name: avd
          no-window: true
          restore-gradle-cache-prefix: v1
          post-emulator-launch-assemble-command: ./gradlew assemble

      - android/run-tests:
          test-command: ./gradlew testSnapshotDebugUnitTest
      - android/run-tests:
          test-command: ./gradlew connectedSnapshotDebugAndroidTest
      - android/save-gradle-cache:
          cache-prefix: v1

      - store_test_results:
          path: survey_app/build/outputs/androidTest-results

      - store_artifacts:
          name: Store Test Results
          path: survey_app/build/outputs/androidTest-results
      - store_artifacts:
          name: Store Test Reports
          path: tables_app/build/reports

  build:
    docker:
      - image: cimg/android:2024.01
    steps:
      - checkout
      - run:
          name: Chmod Permissions
          command: sudo chmod +x gradlew
      - android/restore-gradle-cache:
          cache-prefix: v1
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - android/save-gradle-cache:
          cache-prefix: v1
      - run:
          name: Build Survey
          command: ./gradlew assembleSnapshotDebug

      - persist_to_workspace:
          root: .
          paths:
            - "survey_app/build/outputs"

      - store_artifacts:
          name: Store Build Artifacts
          path: survey_app/build/outputs/apk

#  deploy:
#    docker:
#      - image: cimg/go:1.21.6
#    steps:
#      - attach_workspace:
#          at: .
#      - run:
#          name: Deploy Build to Github
#          command: |
#            go install github.com/tcnksm/ghr@latest
#            echo "export SHORT_HASH=$(echo $CIRCLE_SHA1 | cut -c -7)" >> $BASH_ENV
#            VERSION=v1
#            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./survey_app/build/outputs/apk/demoBasic/debug/survey_app-demo-basic-debug.apk



workflows:
  build-test-deploy-workflow:
    jobs:
      - build
      - test:
          requires:
            - build
#      - deploy:
#          requires:
#            - build